name: flame_example
description: A set of small game examples showcasing all the features provided by the Flame Engine.
publish_to: 'none'

version: 0.1.0-rc2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flame: 1.0.0-rc6
  dashbook: 0.0.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/animations/chopper.png
    - assets/images/animations/chopper.json
    - assets/images/animations/creature.png
    - assets/images/android.png
    - assets/images/tile_maps/selector.png
    - assets/images/tile_maps/tiles.png
