name: flame_example
description: A set of small game examples showcasing all the features provided by the Flame Engine.
publish_to: 'none'

version: 0.1.0-rc1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flame: 1.0.0-rc5
  flame_audio: 0.1.0-rc3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

